bf16: true
cutoff_len: 1024
dataset: upstream-task-restaurant
ddp_timeout: 180000000
do_train: true
eval_steps: 0.15
eval_strategy: steps
finetuning_type: lora
gradient_accumulation_steps: 4
learning_rate: 6.0e-05
load_best_model_at_end: true
logging_steps: 10
lora_alpha: 32
lora_rank: 32
lora_target: q_proj,k_proj,v_proj,o_proj
lr_scheduler_type: cosine
model_name_or_path: /share/home/12351018/pre-train/OpenOrca-Platypus2-13B
num_train_epochs: 3.0
output_dir: jellyfish-rag/outputs/13B/upstream-task/upstream-task-restaurant
overwrite_cache: true
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
plot_loss: true
preprocessing_num_workers: 16
report_to: wandb
save_steps: 0.15
save_total_limit: 10
stage: sft
template: jellyfish-13B
val_size: 0.1
warmup_ratio: 0.1
